const CANVAS_WIDTH = 1200;
const CANVAS_HEIGHT = 1000;
const CELL_SIZE = 30;
const RADIUS = 10;
const BATTLEFIELD_WIDTH = CELL_SIZE * 10;
const BATTLEFIELD_HEIGHT = CELL_SIZE * 10;

const PREPARATION_SCREEN_START_FIELD_COORD_X = 10;
const PREPARATION_SCREEN_START_FIELD_COORD_Y = 300;

const BACKGROUND_COLOR_SHIP = '#B3B3B3';
const UNKNOWN_COLOR = '#f29e1f';
const BORDER_COLOR_SHIP = '#818181';
const EMPTY_COLOR = '#19d470';
const OCCUPIED_COLOR = '#1938d4';
const MISSED_COLOR = '#8c19d4';
const BURNING_COLOR = '#b31569';
const DESTROYED_COLOR = '#e33232';

const shipDatas = [
	{
		id: 1,
		size: 4,
		startPosition: {
			x: 65 + PREPARATION_SCREEN_START_FIELD_COORD_X,
			y: 190 + PREPARATION_SCREEN_START_FIELD_COORD_Y,
		},
		position: {
			x: 65 + PREPARATION_SCREEN_START_FIELD_COORD_X,
			y: 190 + PREPARATION_SCREEN_START_FIELD_COORD_Y,
		},
		cells: [],
		color: BACKGROUND_COLOR_SHIP,
		borderColor: BORDER_COLOR_SHIP,
	},
	{
		id: 2,
		size: 3,
		startPosition: {
			x: 15 + PREPARATION_SCREEN_START_FIELD_COORD_X,
			y: 135 + PREPARATION_SCREEN_START_FIELD_COORD_Y,
		},
		position: {
			x: 15 + PREPARATION_SCREEN_START_FIELD_COORD_X,
			y: 135 + PREPARATION_SCREEN_START_FIELD_COORD_Y,
		},
		cells: [],
		color: BACKGROUND_COLOR_SHIP,
		borderColor: BORDER_COLOR_SHIP,
	},
	{
		id: 3,
		size: 3,
		startPosition: {
			x: 155 + PREPARATION_SCREEN_START_FIELD_COORD_X,
			y: 135 + PREPARATION_SCREEN_START_FIELD_COORD_Y,
		},
		position: {
			x: 155 + PREPARATION_SCREEN_START_FIELD_COORD_X,
			y: 135 + PREPARATION_SCREEN_START_FIELD_COORD_Y,
		},
		cells: [],
		color: BACKGROUND_COLOR_SHIP,
		borderColor: BORDER_COLOR_SHIP,
	},
];

export {
	CANVAS_WIDTH,
	CANVAS_HEIGHT,
	CELL_SIZE,
	shipDatas,
	BATTLEFIELD_WIDTH,
	BATTLEFIELD_HEIGHT,
	EMPTY_COLOR,
	OCCUPIED_COLOR,
	MISSED_COLOR,
	BURNING_COLOR,
	DESTROYED_COLOR,
	RADIUS,
	PREPARATION_SCREEN_START_FIELD_COORD_X,
	PREPARATION_SCREEN_START_FIELD_COORD_Y,
	BORDER_COLOR_SHIP,
	UNKNOWN_COLOR,
};
