FROM nginx:latest

RUN apt-get update \
	&& apt-get install -y openssl \
	&& apt-get install -y nginx-extras \
    && apt-get clean

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir /certs
WORKDIR /certs
RUN openssl genrsa -out devcert.key 2048 \
	&& openssl req -new -key devcert.key -out devcert.csr -subj "/C=RU/ST=/L=/O=Lunatics/CN=${DOMAIN}" \
	&& openssl x509 -req -days 365 -in devcert.csr -signkey devcert.key -out devcert.crt

CMD ["nginx", "-g", "daemon off;"]
