export const PATHS = {
	home: '/',
	test: '/test',
	mainMenu: '/mainmenu',
	mainMenuPlayOnline: '/mainmenu/playOnline/',
	mainMenuPlayAgainstAI: '/mainmenu/playAgainstAI/',
	mainMenuSettings: '/mainmenu/settings/',
	page500: '/page500',
	page404: '*',
	register: '/register',
	forum: '/forum',
	topic: '/forum/topic',
	auth: '/auth',
	profile: '/profile',
	placement: '/placement',
	game: '/game',
	gameCanvas: '/gameCanvas',
	gameResults: '/gameResults',
	profileChangePassword: '/profileChangePassword',
	gameMechanicsDemonstration: '/gameMechanicsDemonstration',
	leaderboard: '/leaderboard',
};
