version: "3"
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - ../.env
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - awesome
volumes:
  pgadmin-data:

networks:
  awesome:
    driver: bridge
